project_id = "cyopwkfinqpsnnpqmmkb"

[functions.liteapi]
verify_jwt = false

[functions.submit-to-google]
verify_jwt = false

[functions.process-price-alerts]
verify_jwt = false

[functions.admin-get-price-alert-jobs]
verify_jwt = true
